tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "git"
brew "gmp"
brew "gnupg"
brew "libyaml"
brew "postgresql", restart_service: true
brew "sqlite"
brew "zlib"
